spring:
  application:
    name: kafka-dlt
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: kafka-dlt-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        metadata.max.age.ms: 10000
  threads:
    virtual:
      enabled: true
  mongodb:
    uri: mongodb://localhost:27017/kafka_mono

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

kafka:
  dlt:
    threshold:
      check-interval: 60000
      window-minutes: 60
      max-count: 10

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL:}
