spring:
  application:
    name: kafka-sample
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: kafka-sample-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      max-poll-records: 500
  threads:
    virtual:
      enabled: true
  mongodb:
    uri: mongodb://localhost:27017/kafka_mono

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

kafka:
  listener:
    payment:
      concurrency: 3
      ack-mode: BATCH
      sync-commits: true
      poll-timeout: 5000
      batch-listener: false
    product:
      concurrency: 3
      ack-mode: BATCH
      sync-commits: true
      poll-timeout: 5000
      batch-listener: false

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL:}
